/**
 * generate-types.ts — derive TypeScript types from the canonical JSON Schema.
 *
 * Single source of truth: `schemas/workspace-state.schema.json` (committed in
 * the repo root). The Rust backend enforces the same constraints via
 * `WorkspaceState::validate()` (see archctl/src/view/workspace.rs).
 *
 * ADR-041 designates the JSON Schema as the contract; we never hand-write the
 * TypeScript types because that would create drift with the schema. If you need
 * to extend the workspace state, edit the schema first, then run this script.
 */

import { compileFromFile } from "json-schema-to-typescript";
import { writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const SCHEMA_PATH = resolve(__dirname, "..", "..", "schemas", "workspace-state.schema.json");
const OUTPUT_PATH = resolve(__dirname, "..", "src", "lib", "workspace.types.ts");

const banner = `// AUTOGENERATED — DO NOT EDIT.
// Source: schemas/workspace-state.schema.json (ADR-041).
// Regenerate via: pnpm generate-types
`;

async function main() {
  const ts = await compileFromFile(SCHEMA_PATH, {
    banner,
    style: {
      singleQuote: false,
      semicolons: true,
      printWidth: 100,
    },
    unreachableDefinitions: "skip",
    strict: true,
  });
  writeFileSync(OUTPUT_PATH, ts, "utf8");
  console.log(`Wrote ${OUTPUT_PATH}`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
