/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface HttpsArchctlLocalSchemasWorkspaceStateSchemaJson {
  /**
   * Literal fijo. Bump para migraciones de schema.
   */
  version: "1.0";
  /**
   * blake3 hex del project identity (64 chars).
   */
  project_hash: string;
  workspace: Workspace;
  /**
   * ISO-8601 con timezone de la última escritura.
   */
  updated_at: string;
}
/**
 * This interface was referenced by `HttpsArchctlLocalSchemasWorkspaceStateSchemaJson`'s JSON-Schema
 * via the `definition` "Workspace".
 */
export interface Workspace {
  camera: {
    x: number;
    y: number;
  };
  /**
   * Nivel de zoom. Rango 0–100 por seguridad.
   */
  zoom: number;
  filters: Filter[];
  selection: null | Selection;
}
/**
 * This interface was referenced by `HttpsArchctlLocalSchemasWorkspaceStateSchemaJson`'s JSON-Schema
 * via the `definition` "Filter".
 */
export interface Filter {
  kind: "c4" | "call-graph" | "sequence" | "class" | "package";
  /**
   * Predicado de filtro validado client-side.
   */
  predicate: string;
}
/**
 * This interface was referenced by `HttpsArchctlLocalSchemasWorkspaceStateSchemaJson`'s JSON-Schema
 * via the `definition` "Selection".
 */
export interface Selection {
  kind: "c4" | "call-graph" | "sequence" | "class" | "package" | "node";
  /**
   * Identificador del elemento seleccionado en el grafo.
   */
  id: string;
}
