/**
 * DriftView — compares a "declared" C4 bundle (manual expected state)
 * against an "actual" C4 bundle (generated by `archctl code c4-discover`).
 *
 * Diff algorithm:
 *   - Match elements by id
 *   - Categorize: added (in actual, not declared), removed (in declared,
 *     not actual), changed (in both, with diffs in name/description/
 *     technology/relations)
 *   - Match relations by (source, target, predicate_id) tuples
 *
 * M17.6 MVP: side-by-side summary + lists per category. M17.6.1 can
 * upgrade to a diff visualizer (highlights on C4View).
 */

import { For, Show, createMemo, type Component } from "solid-js";
import type { GraphEdge, GraphNode, GraphBundle } from "../bundle/loader";

export interface DriftViewProps {
  declared: GraphBundle | null;
  actual: GraphBundle | null;
  onSelect: (id: string | null) => void;
}

type ElementDiff =
  | { kind: "added"; node: GraphNode }
  | { kind: "removed"; node: GraphNode }
  | { kind: "changed"; node: GraphNode; changes: string[] };

type RelationDiff =
  | { kind: "added"; edge: GraphEdge }
  | { kind: "removed"; edge: GraphEdge }
  | { kind: "changed"; edge: GraphEdge; changes: string[] };

export const DriftView: Component<DriftViewProps> = (props) => {
  const elementDiffs = createMemo<ElementDiff[]>(() => {
    const dec = props.declared;
    const act = props.actual;
    if (!dec || !act) return [];

    const decMap = new Map<string, GraphNode>();
    const actMap = new Map<string, GraphNode>();
    for (const n of dec.nodes) decMap.set(n.id, n);
    for (const n of act.nodes) actMap.set(n.id, n);

    const result: ElementDiff[] = [];

    // Added: in actual, not in declared
    for (const [id, node] of actMap) {
      if (!decMap.has(id)) {
        result.push({ kind: "added", node });
      }
    }

    // Removed: in declared, not in actual
    for (const [id, node] of decMap) {
      if (!actMap.has(id)) {
        result.push({ kind: "removed", node });
      }
    }

    // Changed: in both, with property diffs
    for (const [id, decNode] of decMap) {
      const actNode = actMap.get(id);
      if (!actNode) continue;
      const changes = diffElementProps(decNode, actNode);
      if (changes.length > 0) {
        result.push({ kind: "changed", node: actNode, changes });
      }
    }
    return result;
  });

  const relationDiffs = createMemo<RelationDiff[]>(() => {
    const dec = props.declared;
    const act = props.actual;
    if (!dec || !act) return [];

    const keyOf = (e: GraphEdge): string =>
      `${e.source}\0${e.target}\0${e.kind ?? ""}`;

    const decMap = new Map<string, GraphEdge>();
    const actMap = new Map<string, GraphEdge>();
    for (const e of dec.edges) decMap.set(keyOf(e), e);
    for (const e of act.edges) actMap.set(keyOf(e), e);

    const result: RelationDiff[] = [];

    for (const [k, edge] of actMap) {
      if (!decMap.has(k)) result.push({ kind: "added", edge });
    }
    for (const [k, edge] of decMap) {
      if (!actMap.has(k)) result.push({ kind: "removed", edge });
    }
    // (no per-relation prop diff for MVP — relations are matched
    // structurally)
    return result;
  });

  const counts = createMemo(() => {
    const ed = elementDiffs();
    const rd = relationDiffs();
    return {
      added: ed.filter((d) => d.kind === "added").length,
      removed: ed.filter((d) => d.kind === "removed").length,
      changed: ed.filter((d) => d.kind === "changed").length,
      relAdded: rd.filter((d) => d.kind === "added").length,
      relRemoved: rd.filter((d) => d.kind === "removed").length,
    };
  });

  return (
    <div class="drift-view">
      <header class="drift-header">
        <h2>Drift detection</h2>
        <Show
          when={props.declared && props.actual}
          fallback={
            <p class="empty">
              Load both a declared and an actual C4 bundle to see the diff.
            </p>
          }
        >
          <p class="muted">
            declared: {props.declared?.source ?? "—"} · actual:{" "}
            {props.actual?.source ?? "—"}
          </p>
        </Show>
      </header>

      <Show when={props.declared && props.actual}>
        <section class="drift-summary">
          <h3>Summary</h3>
          <div class="drift-counts">
            <span class="drift-count drift-added">
              + {counts().added} added
            </span>
            <span class="drift-count drift-removed">
              − {counts().removed} removed
            </span>
            <span class="drift-count drift-changed">
              ~ {counts().changed} changed
            </span>
            <span class="muted">·</span>
            <span class="drift-count">
              + {counts().relAdded} relations added
            </span>
            <span class="drift-count">
              − {counts().relRemoved} relations removed
            </span>
          </div>
        </section>

        <section class="drift-section">
          <h3>
            <span class="drift-tag drift-added">added</span>
            {counts().added} elements
          </h3>
          <ul>
            <For each={elementDiffs().filter((d) => d.kind === "added")}>
              {(d) => (
                <li>
                  <button
                    class="drift-element"
                    onClick={() => props.onSelect(d.node.id)}
                  >
                    {d.node.label}
                    <span class="drift-element-id">{d.node.id}</span>
                  </button>
                </li>
              )}
            </For>
            <Show
              when={elementDiffs().filter((d) => d.kind === "added").length === 0}
            >
              <li class="muted">none</li>
            </Show>
          </ul>
        </section>

        <section class="drift-section">
          <h3>
            <span class="drift-tag drift-removed">removed</span>
            {counts().removed} elements
          </h3>
          <ul>
            <For each={elementDiffs().filter((d) => d.kind === "removed")}>
              {(d) => (
                <li>
                  <button
                    class="drift-element drift-removed-element"
                    onClick={() => props.onSelect(d.node.id)}
                  >
                    {d.node.label}
                    <span class="drift-element-id">{d.node.id}</span>
                  </button>
                </li>
              )}
            </For>
            <Show
              when={elementDiffs().filter((d) => d.kind === "removed")
                .length === 0}
            >
              <li class="muted">none</li>
            </Show>
          </ul>
        </section>

        <section class="drift-section">
          <h3>
            <span class="drift-tag drift-changed">changed</span>
            {counts().changed} elements
          </h3>
          <ul>
            <For each={elementDiffs().filter((d) => d.kind === "changed")}>
              {(d) => (
                <Show when={d.kind === "changed"}>
                  {(_) => (
                    <li>
                      <button
                        class="drift-element"
                        onClick={() => props.onSelect(d.node.id)}
                      >
                        {d.node.label}
                        <span class="drift-element-id">{d.node.id}</span>
                      </button>
                      <Show when={d.kind === "changed"}>
                        {(_) => (
                          <ul class="drift-changes">
                            <For each={d.changes}>
                              {(change) => <li>{change}</li>}
                            </For>
                          </ul>
                        )}
                      </Show>
                    </li>
                  )}
                </Show>
              )}
            </For>
            <Show
              when={elementDiffs().filter((d) => d.kind === "changed")
                .length === 0}
            >
              <li class="muted">none</li>
            </Show>
          </ul>
        </section>
      </Show>
    </div>
  );
};

/** Return a list of human-readable property diffs between two nodes. */
function diffElementProps(dec: GraphNode, act: GraphNode): string[] {
  const changes: string[] = [];
  if (dec.label !== act.label) {
    changes.push(`label: "${dec.label}" → "${act.label}"`);
  }
  if (dec.kind !== act.kind) {
    changes.push(`kind: ${dec.kind} → ${act.kind}`);
  }
  if ((dec.meta?.description as string) !== (act.meta?.description as string)) {
    changes.push(`description changed`);
  }
  if ((dec.meta?.technology as string) !== (act.meta?.technology as string)) {
    changes.push(`technology changed`);
  }
  return changes;
}