// ADR-0002 + ADR-0005 — IR → Structurizr `workspace.dsl` projection.
//
// Pure function: same IR in → identical DSL out. No LLM, no layout decisions
// beyond what Structurizr's auto-layout produces. The projection is the
// single sink for the IR; downstream renderers (Structurizr `local` viewer,
// pinned headless CLI for export) never re-parse the IR.
import type { ArchitectureIR, IRElement, IRRelationship } from "../ir/ir.ts";

const KIND_TO_STRUCTURIZR: Record<IRElement["kind"], string> = {
  person: "Person",
  softwareSystem: "SoftwareSystem",
  container: "Container",
  component: "Component",
  codeElement: "Component",
};

function elementSlug(id: string): string {
  // Structurizr DSL identifiers must match `[A-Za-z0-9-_]+`. The IR uses
  // `<kind>:<kebab-name>`; we keep the kebab portion and replace `:` with `_`
  // so the DSL stays readable.
  return id.replace(/[:]/g, "_");
}

function relationshipSlug(id: string): string {
  return id.replace(/[:]/g, "_");
}

export interface ProjectionResult {
  dsl: string;
  warnings: string[];
}

/**
 * Project an ArchitectureIR v1 into a Structurizr `workspace.dsl` string.
 *
 * Constraints (intentional, not bugs):
 *   - The DSL identifier for an element/relationship is the IR id with `:`
 *     replaced by `_`; this keeps the DSL human-readable AND stable across
 *     re-projections.
 *   - The DSL name is the IR name (kebab-case → "Kebab Case" for readability).
 *   - Tags, classification, confidence, and method are not yet emitted in
 *     the DSL because Structurizr's DSL does not have a native slot for
 *     them. Phase 4's C4 renderer (or a sidecar JSON) will carry those.
 */
export function projectIRToStructurizr(ir: ArchitectureIR): ProjectionResult {
  const warnings: string[] = [];
  const out: string[] = [];
  out.push(`workspace "archctl" "Generated by archctl from Architecture IR v1" {`);
  out.push("  model {");
  out.push(`    // schemaVersion = ${ir.schemaVersion}`);
  out.push(`    // sourceIdentity = ${ir.sourceIdentitySummary}`);
  out.push("");

  for (const e of ir.elements) {
    const kind = KIND_TO_STRUCTURIZR[e.kind] ?? "Component";
    const slug = elementSlug(e.id);
    if (kind === "Person" && e.kind !== "person") {
      warnings.push(`element ${e.id}: kind=${e.kind} mapped to Person fallback`);
    }
    const techProp = e.technology && e.technology.length > 0
      ? ` "${escapeDsl(e.technology.join(", "))}"`
      : "";
    const descProp = e.description
      ? ` "${escapeDsl(e.description)}"`
      : "";
    out.push(`    ${kind.toLowerCase()} ${slug} "${escapeDsl(toTitle(e.name))}" "${escapeDsl(toTitle(e.name))}"${techProp}${descProp} {`);
    if (e.tags && e.tags.length > 0) {
      out.push(`      tags "${escapeDsl(e.tags.join(","))}"`);
    }
    out.push("    }");
  }

  out.push("");
  for (const r of ir.relationships) {
    const src = elementSlug(r.source);
    const tgt = elementSlug(r.target);
    const desc = r.description ?? "";
    const tech = r.technology ?? "";
    const via = r.via ?? "";
    out.push(`    ${src} -> ${tgt} "${escapeDsl(desc)}" "${escapeDsl(tech)}"${via ? ` // ${escapeDsl(via)}` : ""}`);
  }

  out.push("  }");
  out.push("}");
  out.push("");

  // Auto-rendered views — minimal; the user-facing renderer decides layout.
  out.push("  views {");
  out.push("    systemContext archctx \"SystemContext\" { include * }");
  out.push("    styles {");
  out.push("      element \"Person\" { shape Person }");
  out.push("      element \"SoftwareSystem\" { background #1168bd color #ffffff }");
  out.push("      element \"Container\" { background #438dd5 color #ffffff }");
  out.push("      element \"Component\" { background #85bbf0 color #000000 }");
  out.push("      element \"Code\" { background #999999 color #ffffff }");
  out.push("    }");
  out.push("  }");
  return { dsl: out.join("\n"), warnings };
}

function toTitle(s: string): string {
  return s.replace(/[-_]+/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
}

function escapeDsl(s: string): string {
  // DSL strings are double-quoted; escape internal quotes.
  return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

export function projectRelationship(r: IRRelationship): string {
  // Public for tests that want to compare single-relationship strings.
  const src = elementSlug(r.source);
  const tgt = elementSlug(r.target);
  return `${src} -> ${tgt} "${escapeDsl(r.description ?? "")}"`;
}

export function projectElement(e: IRElement): string {
  const kind = KIND_TO_STRUCTURIZR[e.kind] ?? "Component";
  return `${kind.toLowerCase()} ${elementSlug(e.id)} "${escapeDsl(toTitle(e.name))}"`;
}
