#![cfg(feature = "test-fixtures")]

//! Shared bench fixtures for the archctl criterion harness.
//!
//! Each `seed_*` function builds a fresh `LbugStore`, applies the schema
//! migrations, and inserts the canonical dataset's elements + relations
//! via bulk Cypher. The bench function then runs the operation under
//! measurement. Each call uses its own `TempDir` so the `fs2` flock
//! acquires cleanly (no cross-bench contention).
//!
//! Datasets live at `benchmarks/datasets/{small,medium,large}.json` and
//! are regenerated by `scripts/generate_bench_datasets.py` (deterministic
//! seed 0xC0DE0001).

use std::path::PathBuf;

use archctl::store::{GraphStore, LbugStore};
use tempfile::TempDir;

const DATASET_SMALL: &str = "../../benchmarks/datasets/small-100.json";
const DATASET_MEDIUM: &str = "../../benchmarks/datasets/medium-1k.json";
#[allow(dead_code)]
const DATASET_LARGE: &str = "../../benchmarks/datasets/large-10k.json";

/// Returns `(store, _tmp)` ready for measurement. Drops `_tmp` on scope
/// exit to release the `fs2` flock and the on-disk `.lbdb`.
pub fn seed_small() -> (LbugStore, TempDir) {
    seed(DATASET_SMALL)
}

pub fn seed_medium() -> (LbugStore, TempDir) {
    seed(DATASET_MEDIUM)
}

#[allow(dead_code)]
pub fn seed_large() -> (LbugStore, TempDir) {
    seed(DATASET_LARGE)
}

fn seed(dataset_path: &str) -> (LbugStore, TempDir) {
    let tmp = tempfile::tempdir().expect("tempdir");
    let project = tmp.path().join("proj");
    std::fs::create_dir_all(&project).expect("mkdir proj");

    let mut store = LbugStore::open(&project).expect("LbugStore::open");
    store.init().expect("store.init");

    // Resolve dataset path relative to the workspace root (one level
    // up from archctl/, where `benchmarks/datasets/` lives).
    let mut path = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    path.pop(); // archctl/ → workspace root
    path.push(dataset_path.trim_start_matches("../"));

    let bytes = std::fs::read(&path).unwrap_or_else(|e| {
        panic!(
            "failed to read dataset fixture {}: {} — run scripts/generate_bench_datasets.py",
            path.display(),
            e
        )
    });

    let dataset: Dataset = serde_json::from_slice(&bytes).expect("parse dataset JSON");

    // Seed MetaType + Predicate rows so the elements+relations can be
    // MERGEd against existing node labels.
    seed_meta_predicate(&mut store);

    // Bulk insert elements.
    for el in &dataset.elements {
        let id = el.e_id.as_str();
        let kind = el.e_kind_id.as_str();
        let cat = el.e_category.as_str();
        let key = el.e_canonical_key.as_str();
        let name = el.e_current_name.as_str();
        let status = el.e_current_status.as_str();
        let conf = el.e_current_confidence;
        let vid = el.e_current_version_id.as_str();
        // Validate identifiers (allowlist path) to defend against
        // accidentally-generated fixture data.
        let id = archctl::graph::validate_identifier(id).expect("id");
        let kind = archctl::graph::validate_identifier(kind).expect("kind");
        let cat = archctl::graph::validate_identifier(cat).expect("cat");
        let key = archctl::graph::validate_identifier(key).expect("key");
        let name_safe = name.replace('\'', "\\'");
        let status_safe = status.replace('\'', "\\'");
        let vid = archctl::graph::validate_identifier(vid).expect("vid");

        let cypher = format!(
            "MERGE (e:Element {{id: '{id}'}}) SET \
             e.kind_id = '{kind}', e.category = '{cat}', \
             e.canonical_key = '{key}', e.current_name = '{name_safe}', \
             e.current_status = '{status_safe}', e.current_confidence = {conf}, \
             e.current_version_id = '{vid}';"
        );
        // Use execute_raw_cypher_for_test — the test escape hatch bypasses
        // the RawGraphQuery is_read_only_query guard so writes (MERGE /
        // CREATE) are allowed in bench fixtures.
        store
            .execute_raw_cypher_for_test(&cypher)
            .expect("seed element write");
    }

    // Bulk insert relations.
    // Mirrors the `link_semantic_edge` pattern: MERGE on (src)-[r:SEMANTIC_EDGE]->(tgt)
    // keyed by relation_id, then SET additional properties. This avoids the
    // Kùzu restriction on inline REL-TABLE properties in CREATE.
    for rel in &dataset.relations {
        let rid = rel.edge_relation_id.as_str();
        let pid = rel.edge_predicate_id.as_str();
        let src = rel.src_id.as_str();
        let tgt = rel.tgt_id.as_str();
        let rid = archctl::graph::validate_identifier(rid).expect("rid");
        let pid = archctl::graph::validate_identifier(pid).expect("pid");
        let src = archctl::graph::validate_identifier(src).expect("src");
        let tgt = archctl::graph::validate_identifier(tgt).expect("tgt");
        let order: i64 = rel.edge_order_key.parse().ok().unwrap_or(0);
        let props_safe = rel.edge_props.replace('\'', "\\'");

        let cypher = format!(
            "MATCH (a:Element {{id: '{src}'}}), (b:Element {{id: '{tgt}'}}) \
             MERGE (a)-[r:SEMANTIC_EDGE {{relation_id: '{rid}'}}]->(b) \
             SET r.predicate_id = '{pid}', r.order_key = {order}, r.props = '{props_safe}', r.active = true;"
        );
        store
            .execute_raw_cypher_for_test(&cypher)
            .expect("seed relation write");
    }

    (store, tmp)
}

fn seed_meta_predicate(store: &mut LbugStore) {
    // Minimum MetaType + Predicate rows so element/relation seeds don't
    // trip FK-style constraints in the canonical schema.
    let meta_types = [
        "mt.system",
        "mt.container",
        "mt.component",
        "mt.code",
        "mt.deployment",
        "mt.person",
        "mt.datastore",
        "mt.external",
    ];
    for mt in meta_types {
        let mt = archctl::graph::validate_identifier(mt).expect("mt");
        store
            .execute_raw_cypher_for_test(&format!("MERGE (:MetaType {{id: '{mt}'}});"))
            .expect("seed metatype write");
    }
    let predicates = [
        "p.calls",
        "p.depends_on",
        "p.uses",
        "p.owns",
        "p.contains",
        "p.flows_to",
    ];
    for p in predicates {
        let p = archctl::graph::validate_identifier(p).expect("p");
        store
            .execute_raw_cypher_for_test(&format!("MERGE (:Predicate {{id: '{p}'}});"))
            .expect("seed predicate write");
    }
}

// ============================================================================
// Dataset deserialization (matches scripts/generate_bench_datasets.py output)
// ============================================================================

#[derive(Debug, serde::Deserialize)]
pub struct Dataset {
    pub elements: Vec<ElementRow>,
    pub relations: Vec<RelationRow>,
    #[serde(default)]
    #[allow(dead_code)]
    pub versions: Vec<VersionRow>,
}

#[derive(Debug, serde::Deserialize)]
pub struct ElementRow {
    #[serde(rename = "e.id")]
    pub e_id: String,
    #[serde(rename = "e.kind_id")]
    pub e_kind_id: String,
    #[serde(rename = "e.category")]
    pub e_category: String,
    #[serde(rename = "e.canonical_key")]
    pub e_canonical_key: String,
    #[serde(rename = "e.current_name")]
    pub e_current_name: String,
    #[serde(rename = "e.current_status")]
    pub e_current_status: String,
    #[serde(rename = "e.current_confidence")]
    pub e_current_confidence: f64,
    #[serde(rename = "e.current_version_id")]
    pub e_current_version_id: String,
}

#[derive(Debug, serde::Deserialize)]
pub struct RelationRow {
    #[serde(rename = "edge.relation_id")]
    pub edge_relation_id: String,
    #[serde(rename = "edge.predicate_id")]
    pub edge_predicate_id: String,
    #[serde(rename = "src.id")]
    pub src_id: String,
    #[serde(rename = "tgt.id")]
    pub tgt_id: String,
    #[serde(rename = "edge.order_key")]
    pub edge_order_key: String,
    #[serde(rename = "edge.props")]
    pub edge_props: String,
}

#[derive(Debug, serde::Deserialize)]
#[allow(dead_code)]
pub struct VersionRow {
    #[serde(rename = "v.id")]
    pub v_id: String,
    #[serde(rename = "v.name")]
    pub v_name: String,
    #[serde(rename = "v.description")]
    pub v_description: String,
    #[serde(rename = "v.props")]
    pub v_props: String,
}

// Reference Dataset::versions (and its fields) so future bench
// variants that exercise ElementVersion reads compile cleanly.
#[allow(dead_code)]
fn _ensure_versions_used(d: &Dataset) -> usize {
    d.versions.len()
}
