/**
 * DriftView — compares a "declared" C4 bundle (manual expected
 * state) against an "actual" C4 bundle (generated by
 * `archctl code c4-discover`).
 *
 * Visual: a G6 dagre vertical graph of the *actual* bundle, with
 * per-node color encoding the diff category:
 *   - added: amber (in actual, not declared)
 *   - removed: red (in declared, not actual)
 *   - changed: yellow
 *   - unchanged: blue (default)
 *
 * The previous side-by-side list render was text-heavy; the
 * graph view makes drift scannable in one glance.
 *
 * M17.1.6 — graph view. Pure diff logic in DriftGraph.ts.
 */

import {
  For,
  Show,
  createEffect,
  createMemo,
  onCleanup,
  onMount,
  type Component,
} from "solid-js";
import type { GraphBundle, GraphNode } from "../bundle/loader";
import { GraphRenderer } from "../renderer/g6";
import { TB_LAYERED } from "../renderer/layout-presets";
import { diffElements, driftCounts, type ElementDiff } from "./DriftGraph";

export interface DriftViewProps {
  declared: GraphBundle | null;
  actual: GraphBundle | null;
  onSelect: (id: string | null) => void;
}

const CATEGORY_FILL: Record<ElementDiff["category"], string> = {
  added: "#fbbf24",
  removed: "#f87171",
  changed: "#facc15",
  unchanged: "#5b8def",
};

export const DriftView: Component<DriftViewProps> = (props) => {
  let containerRef!: HTMLDivElement;
  let renderer: GraphRenderer | undefined;

  const elementDiffs = createMemo<ElementDiff[]>(() => {
    if (!props.declared || !props.actual) return [];
    return diffElements(props.declared.nodes, props.actual.nodes);
  });

  const counts = createMemo(() => driftCounts(elementDiffs(), []));

  const visibleNodes = createMemo<GraphNode[]>(() => {
    const a = props.actual;
    if (!a) return [];
    return a.nodes;
  });

  const visibleEdges = createMemo(() => {
    const a = props.actual;
    if (!a) return [];
    return a.edges;
  });

  /** Per-node style config: color by diff category. */
  const styleConfig = createMemo(() => {
    const byKind: Record<string, string> = {};
    for (const d of elementDiffs()) {
      byKind[d.id] = CATEGORY_FILL[d.category];
    }
    return {
      byKind,
      defaultFill: "#5b8def",
      defaultStroke: "#1f3a5f",
      selectedStroke: "#fbbf24",
    };
  });

  onMount(() => {
    renderer = new GraphRenderer({
      container: containerRef,
      width: containerRef?.clientWidth || 800,
      height: containerRef?.clientHeight || 600,
      // M19: ELK layered in Web Worker, top-to-bottom.
      layoutOptions: TB_LAYERED,
      onNodeClick: (id) => {
        props.onSelect(id);
      },
    });
    renderer.setData({
      schemaVersion: "0.0.0",
      source: "drift-view",
      loadedAt: "0",
      rawKind: "c4",
      nodes: visibleNodes(),
      edges: visibleEdges(),
    });
  });

  createEffect(() => {
    if (!renderer) return;
    renderer.setNodeStyle(styleConfig());
    renderer.setData({
      schemaVersion: "0.0.0",
      source: "drift-view",
      loadedAt: "0",
      rawKind: "c4",
      nodes: visibleNodes(),
      edges: visibleEdges(),
    });
  });

  onMount(() => {
    if (typeof ResizeObserver === "undefined") return;
    const ro = new ResizeObserver((entries) => {
      const entry = entries[0];
      if (!entry || !renderer) return;
      const { width, height } = entry.contentRect;
      if (width > 0 && height > 0) renderer.resize(width, height);
    });
    ro.observe(containerRef);
    onCleanup(() => ro.disconnect());
  });

  onCleanup(() => {
    renderer?.destroy();
    renderer = undefined;
  });

  return (
    <div class="drift-view">
      <header class="drift-header">
        <h2>Drift detection</h2>
        <Show
          when={props.declared && props.actual}
          fallback={
            <p class="empty">
              Load both a declared and an actual C4 bundle to see the diff.
            </p>
          }
        >
          <p class="muted">
            declared: {props.declared?.source ?? "—"} · actual:{" "}
            {props.actual?.source ?? "—"}
          </p>
        </Show>
      </header>

      <Show when={props.declared && props.actual}>
        <div class="drift-summary">
          <span class="legend-chip" style={{ color: CATEGORY_FILL.added }}>
            + {counts().added} added
          </span>
          <span class="legend-chip" style={{ color: CATEGORY_FILL.removed }}>
            − {counts().removed} removed
          </span>
          <span class="legend-chip" style={{ color: CATEGORY_FILL.changed }}>
            ~ {counts().changed} changed
          </span>
          <span class="legend-chip" style={{ color: CATEGORY_FILL.unchanged }}>
            = {counts().unchanged} unchanged
          </span>
        </div>

        <div ref={containerRef} class="drift-canvas" />

        <section class="drift-details">
          <h3>Element diffs</h3>
          <ul>
            <For each={elementDiffs()}>
              {(d) => {
                const node = visibleNodes().find((n) => n.id === d.id);
                return (
                  <li class={`drift-row drift-${d.category}`}>
                    <span class="drift-marker">{markerFor(d.category)}</span>
                    <Show when={node} fallback={<code>{d.id}</code>}>
                      <code>{node!.label}</code>
                    </Show>
                    <span class="muted">{d.category}</span>
                  </li>
                );
              }}
            </For>
          </ul>
        </section>
      </Show>
    </div>
  );
};

function markerFor(category: ElementDiff["category"]): string {
  switch (category) {
    case "added":
      return "+";
    case "removed":
      return "−";
    case "changed":
      return "~";
    case "unchanged":
      return "=";
  }
}
