/**
 * DriftView — compares a "declared" C4 bundle (manual expected state)
 * against an "actual" C4 bundle (generated by `archctl code c4-discover`).
 *
 * Diff algorithm:
 *   - Match elements by id
 *   - Categorize: added (in actual, not declared), removed (in declared,
 *     not actual), changed (in both, with diffs in name/description/
 *     technology/relations)
 *   - Match relations by (source, target, predicate_id) tuples
 *
 * M17.6 MVP: side-by-side summary + lists per category. M17.6.1 can
 * upgrade to a diff visualizer (highlights on C4View).
 */

import { For, Show, createMemo, type Component } from "solid-js";
import type { GraphBundle } from "../bundle/loader";
import {
  diffElements,
  diffRelations,
  driftCounts,
  type ElementDiff,
  type RelationDiff,
} from "./DriftGraph";

export interface DriftViewProps {
  declared: GraphBundle | null;
  actual: GraphBundle | null;
  onSelect: (id: string | null) => void;
}

export const DriftView: Component<DriftViewProps> = (props) => {
  const elementDiffs = createMemo<ElementDiff[]>(() => {
    if (!props.declared || !props.actual) return [];
    return diffElements(props.declared.nodes, props.actual.nodes);
  });

  const relationDiffs = createMemo<RelationDiff[]>(() => {
    if (!props.declared || !props.actual) return [];
    return diffRelations(props.declared.edges, props.actual.edges);
  });

  const counts = createMemo(() =>
    driftCounts(elementDiffs(), relationDiffs()),
  );

  return (
    <div class="drift-view">
      <header class="drift-header">
        <h2>Drift detection</h2>
        <Show
          when={props.declared && props.actual}
          fallback={
            <p class="empty">
              Load both a declared and an actual C4 bundle to see the diff.
            </p>
          }
        >
          <p class="muted">
            declared: {props.declared?.source ?? "—"} · actual:{" "}
            {props.actual?.source ?? "—"}
          </p>
        </Show>
      </header>

      <Show when={props.declared && props.actual}>
        <section class="drift-summary">
          <h3>Summary</h3>
          <div class="drift-counts">
            <span class="drift-count drift-added">
              + {counts().added} added
            </span>
            <span class="drift-count drift-removed">
              − {counts().removed} removed
            </span>
            <span class="drift-count drift-changed">
              ~ {counts().changed} changed
            </span>
            <span class="muted">·</span>
            <span class="drift-count">
              + {counts().relAdded} relations added
            </span>
            <span class="drift-count">
              − {counts().relRemoved} relations removed
            </span>
          </div>
        </section>

        <section class="drift-section">
          <h3>
            <span class="drift-tag drift-added">added</span>
            {counts().added} elements
          </h3>
          <ul>
            <For each={elementDiffs().filter((d) => d.kind === "added")}>
              {(d) => (
                <li>
                  <button
                    class="drift-element"
                    onClick={() => props.onSelect(d.node.id)}
                  >
                    {d.node.label}
                    <span class="drift-element-id">{d.node.id}</span>
                  </button>
                </li>
              )}
            </For>
            <Show
              when={elementDiffs().filter((d) => d.kind === "added").length === 0}
            >
              <li class="muted">none</li>
            </Show>
          </ul>
        </section>

        <section class="drift-section">
          <h3>
            <span class="drift-tag drift-removed">removed</span>
            {counts().removed} elements
          </h3>
          <ul>
            <For each={elementDiffs().filter((d) => d.kind === "removed")}>
              {(d) => (
                <li>
                  <button
                    class="drift-element drift-removed-element"
                    onClick={() => props.onSelect(d.node.id)}
                  >
                    {d.node.label}
                    <span class="drift-element-id">{d.node.id}</span>
                  </button>
                </li>
              )}
            </For>
            <Show
              when={elementDiffs().filter((d) => d.kind === "removed")
                .length === 0}
            >
              <li class="muted">none</li>
            </Show>
          </ul>
        </section>

        <section class="drift-section">
          <h3>
            <span class="drift-tag drift-changed">changed</span>
            {counts().changed} elements
          </h3>
          <ul>
            <For each={elementDiffs().filter((d) => d.kind === "changed")}>
              {(d) => (
                <Show when={d.kind === "changed"}>
                  {(_) => (
                    <li>
                      <button
                        class="drift-element"
                        onClick={() => props.onSelect(d.node.id)}
                      >
                        {d.node.label}
                        <span class="drift-element-id">{d.node.id}</span>
                      </button>
                      <Show when={d.kind === "changed"}>
                        {(_) => (
                          <ul class="drift-changes">
                            <For each={d.changes}>
                              {(change) => <li>{change}</li>}
                            </For>
                          </ul>
                        )}
                      </Show>
                    </li>
                  )}
                </Show>
              )}
            </For>
            <Show
              when={elementDiffs().filter((d) => d.kind === "changed")
                .length === 0}
            >
              <li class="muted">none</li>
            </Show>
          </ul>
        </section>
      </Show>
    </div>
  );
};
